// Emoji.js — type a name, get the glyph: "shrug", "check", "em dash" in the
// launcher search box, Enter copies it. Covers the emoji picker's common
// ground (its paste path has a pile of open bugs) plus the symbols people
// actually go hunting for: arrows, math, dashes, currency, boxes.
// API: search(query) -> [{ label, glyph }] ranked exact > prefix > contains,
// capped by the caller.

.pragma library

var TABLE = [
  ["shrug", "¯\\_(ツ)_/¯"],
  ["flip table", "(╯°□°)╯︵ ┻━┻"],
  ["unflip table", "┬─┬ ノ( ゜-゜ノ)"],
  ["lol face", "( ͡° ͜ʖ ͡°)"],
  ["heart", "❤️"],
  ["black heart", "🖤"],
  ["sparkle heart", "💖"],
  ["broken heart", "💔"],
  ["fire", "🔥"],
  ["rocket", "🚀"],
  ["party", "🎉"],
  ["tada", "🎉"],
  ["star", "⭐"],
  ["glowing star", "🌟"],
  ["check", "✅"],
  ["green check", "✅"],
  ["white check", "☑️"],
  ["checkbox", "☑️"],
  ["empty checkbox", "☐"],
  ["cross", "❌"],
  ["red x", "❌"],
  ["ballot x", "✗"],
  ["question", "❓"],
  ["exclamation", "❗"],
  ["warning", "⚠️"],
  ["thumbs up", "👍"],
  ["thumbs down", "👎"],
  ["clap", "👏"],
  ["wave", "👋"],
  ["ok hand", "👌"],
  ["eyes", "👀"],
  ["thinking", "🤔"],
  ["facepalm", "🤦"],
  ["shrug face", "🤷"],
  ["skull", "💀"],
  ["ghost", "👻"],
  ["coffee", "☕"],
  ["tea", "🍵"],
  ["beer", "🍺"],
  ["pizza", "🍕"],
  ["bug", "🐛"],
  ["zap", "⚡"],
  ["sun", "☀️"],
  ["moon", "🌙"],
  ["cloud", "☁️"],
  ["umbrella", "☂️"],
  ["snowflake", "❄️"],
  ["rainbow", "🌈"],
  ["leaf", "🍃"],
  ["lock", "🔒"],
  ["unlock", "🔓"],
  ["key", "🔑"],
  ["magnifier", "🔍"],
  ["search", "🔍"],
  ["bell", "🔔"],
  ["bookmark", "🔖"],
  ["pin", "📌"],
  ["clip", "📎"],
  ["scissors", "✂️"],
  ["pencil", "✏️"],
  ["memo", "📝"],
  ["book", "📖"],
  ["gift", "🎁"],
  ["trophy", "🏆"],
  ["medal", "🏅"],
  ["music", "🎵"],
  ["headphones", "🎧"],
  ["microphone", "🎤"],
  ["camera", "📷"],
  ["phone", "📱"],
  ["laptop", "💻"],
  ["desktop", "🖥️"],
  ["keyboard", "⌨️"],
  ["printer", "🖨️"],
  ["wrench", "🔧"],
  ["hammer", "🔨"],
  ["gear", "⚙️"],
  ["link", "🔗"],
  ["chain", "🔗"],
  ["trash", "🗑️"],
  ["flag", "🏁"],
  ["map", "🗺️"],
  ["airplane", "✈️"],
  ["car", "🚗"],
  ["bicycle", "🚲"],
  ["train", "🚆"],
  ["ship", "🚢"],
  ["hourglass", "⏳"],
  ["clock", "🕐"],
  ["watch", "⌚"],
  ["battery", "🔋"],
  ["plug", "🔌"],
  ["arrow up", "↑"],
  ["arrow down", "↓"],
  ["arrow left", "←"],
  ["arrow right", "→"],
  ["arrow up right", "↗"],
  ["arrow down right", "↘"],
  ["arrow up left", "↖"],
  ["arrow down left", "↙"],
  ["double arrow", "⇔"],
  ["long arrow", "⟶"],
  ["em dash", "—"],
  ["en dash", "–"],
  ["horizontal bar", "―"],
  ["ellipsis", "…"],
  ["bullet", "•"],
  ["black bullet", "•"],
  ["white bullet", "◦"],
  ["triangle bullet", "‣"],
  ["hyphen bullet", "⁃"],
  ["degree", "°"],
  ["plus minus", "±"],
  ["multiply", "×"],
  ["divide", "÷"],
  ["almost equal", "≈"],
  ["not equal", "≠"],
  ["less equal", "≤"],
  ["greater equal", "≥"],
  ["infinity", "∞"],
  ["square root", "√"],
  ["sum", "∑"],
  ["product", "∏"],
  ["integral", "∫"],
  ["pi", "π"],
  ["delta", "Δ"],
  ["sigma", "Σ"],
  ["ohm", "Ω"],
  ["micro", "µ"],
  ["euro", "€"],
  ["pound", "£"],
  ["yen", "¥"],
  ["cent", "¢"],
  ["dollar", "$"],
  ["rupee", "₹"],
  ["bitcoin", "₿"],
  ["copyright", "©"],
  ["trademark", "™"],
  ["registered", "®"],
  ["section", "§"],
  ["paragraph", "¶"],
  ["dagger", "†"],
  ["double dagger", "‡"],
  ["quote", "❝"],
  ["black square", "■"],
  ["white square", "□"],
  ["black circle", "●"],
  ["white circle", "○"],
  ["half circle", "◐"],
  ["diamond", "◆"],
  ["lozenge", "◊"],
  ["black star", "★"],
  ["white star", "☆"],
  ["heavy check", "✔"],
  ["heavy x", "✘"],
  ["ballot check", "☑"],
  ["progress dot", "●"],
  ["dot", "·"],
  ["middle dot", "·"],
  ["interpunct", "·"],
  ["curly quotes", "❝❞"],
  ["sharp", "♯"],
  ["flat", "♭"],
  ["natural", "♮"]
]

function search(query, limit) {
  var q = String(query || "").trim().toLowerCase()
  if (q.length < 2) return []
  var max = limit || 4
  var exact = []
  var prefix = []
  var contains = []
  for (var i = 0; i < TABLE.length; i++) {
    var name = TABLE[i][0]
    if (name === q) { exact.push(TABLE[i]); continue }
    if (name.indexOf(q) === 0) { prefix.push(TABLE[i]); continue }
    if (name.indexOf(q) !== -1) contains.push(TABLE[i])
  }
  var out = exact.concat(prefix, contains)
  out = out.slice(0, max)
  var rows = []
  for (var j = 0; j < out.length; j++) {
    rows.push({ name: out[j][0], glyph: out[j][1] })
  }
  return rows
}
